plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-hacker

title: msdocwatch
description: Keep an eye on Microsoft documentation.
